services:
  database:
    container_name: database
    restart: always
    build: ./database
    ports:
      - "10000:10000"
      
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - "8000:8000"

  characters:
    container_name: characters
    restart: always
    build: ./characters
    ports:
      - "8001:8001"
    depends_on:
      - database

  planets:
    container_name: planets
    restart: always
    build: ./planets
    ports:
      - "8003:8003"
    depends_on:
      - database

  films:
    container_name: films
    restart: always
    build: ./films
    ports:
      - "8002:8002"
    depends_on:
      - database

  users:
    container_name: users
    restart: always
    build: ./users
    ports:
      - "8004:8004"
    depends_on:
      - database